### PR TITLE
Updated help part

### PR DESCRIPTION
**Pull request by LWJerri**

### CODE REVIEW

**Comment by Satont** [comment]
I do not like share my personal contacts.

I'll create server for bot later and will update readme.

**Comment by AlexWayfer** [comment]
> I'll create server for bot later and will update readme.

Maybe then it worth to close this issue, not now?

**Comment by Satont** [comment]
> Maybe then it's worth to close this issue, not now?

What do you mean? You mean re-open PR until i'll create Discord server?

**Comment by AlexWayfer** [comment]
> > Maybe then it's worth to close this issue, not now?
> 
> You mean re-open PR until i'll create Discord server? And then update link right in this PR?

I thought it's an issue, not PR, sorry, my bad.

**Pull request closed without merging**
